---
- project:
    merge-mode: squash-merge
    default-branch: devel
    templates:
      - release-notes-jobs
    check:
      jobs:
        - ensure-golangci-lint:
            golangci_lint_version: v1.41.1
        - golangci-lint:
            voting: false
        - golang-make-test
        - golang-make-vet
        - goreleaser-build:
            nodeset: fedora-32-large
    gate:
      jobs:
        - ensure-golangci-lint:
            golangci_lint_version: v1.41.1
        - golangci-lint:
            voting: false
        - golang-make-test
        - golang-make-vet
        - goreleaser-build:
            nodeset: fedora-32-large
    tag:
      jobs:
        - release-goreleaser:
            nodeset: fedora-32-large
